### ISSUE TITLE
Does this library work with any OpenThread BorderRouter

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [home-assistant-libs/python-otbr-api#16]
I have a matter test harness OTBR running. But tying that OTBR in does not work.

It seems the REST API of that ot-br-posix is not offering {self._url}/node/dataset/active  https://github.com/openthread/ot-br-posix/blob/main/src/rest/resource.cpp#L39-L48. {self._url}/node is available.

Do you expect a custom ot-br-posix?

**Comment by markus-becker-tridonic-com** [comment]
Seems to require custom extensions of OTBR https://github.com/home-assistant/addons-development/tree/master/openthread_border_router. Probably you should mention this in the docs, that not every/upstream OTBR would work.

**Comment by alexanderhoet** [comment]
I also have the an issue with my OTBR router running version: OPENTHREAD/9af0bfa; POSIX; Jan 7 2023 10:27:48
The home assistant plugin finds the border router using mdns, but I cannot add it using the REST interface, while I can connect to it using a web browser.

I will apply the plugin and report back if that worked.

**Comment by agners** [comment]
This library implements features which are not yet in the upstream version of the OTBR REST API. But I am working on up-streaming our changes, see https://github.com/openthread/ot-br-posix/pull/1682.

Most likely there will be changes, and this library will have to adjust to this changes at one point.
